// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEoSA6_HXGV9ypVR_D2wXSaTa_4V3st7g',
    appId: '1:373128898734:web:fad0f191ee774ff586253f',
    messagingSenderId: '373128898734',
    projectId: 'techcomputer-91f2f',
    authDomain: 'techcomputer-91f2f.firebaseapp.com',
    storageBucket: 'techcomputer-91f2f.appspot.com',
    measurementId: 'G-BQB42B63ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQgsSht9sjVo1kZNWvf6yX_A6OaaQIzwc',
    appId: '1:373128898734:android:904041f1057380df86253f',
    messagingSenderId: '373128898734',
    projectId: 'techcomputer-91f2f',
    storageBucket: 'techcomputer-91f2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQIz9VQbuyfK5lFOnPglyzzP9qfVv7vwA',
    appId: '1:373128898734:ios:d0b9aac1c10cd67086253f',
    messagingSenderId: '373128898734',
    projectId: 'techcomputer-91f2f',
    storageBucket: 'techcomputer-91f2f.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQIz9VQbuyfK5lFOnPglyzzP9qfVv7vwA',
    appId: '1:373128898734:ios:d0b9aac1c10cd67086253f',
    messagingSenderId: '373128898734',
    projectId: 'techcomputer-91f2f',
    storageBucket: 'techcomputer-91f2f.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
